# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2a498b1b88fdef2e361f286339947907b2e0d8e34f3c70f580c4d4fe2d57dc4fae8a5f4737a361090c906bada923a99cf292ab6afe2ef8f1a80b690c32f93b

test:
  secret_key_base: aad7d92b846edbe7c46a1d0bb383e83acdb75ad2d16f95c4de1cc115fc7563bdfa96bb9c30c08371c3592c7b2d8917cc55e6cebbb9d437c21f058758299e90ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
